spring:
  # 테스트용 H2 데이터베이스
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # JPA 테스트 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true

  # 테스트 환경에서는 Redis 비활성화
  data:
    redis:
      repositories.enabled: false
    elasticsearch:
      repositories.enabled: false

  # 테스트에서는 Flyway 비활성화
  flyway:
    enabled: false

  # 테스트에서는 배치 작업 비활성화
  batch:
    job.enabled: false

# 테스트 환경 로깅 설정
logging:
  level:
    root: WARN
    com.yourusername.devbloghub: DEBUG

# 테스트용 JWT 설정
jwt:
  secret: test-jwt-secret-for-unit-testing
  expiration: 60000  # 1분 (테스트용)